# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10.0-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}{{ checksum "browser-tests/package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
        
      # temp workaround until chrome is updated on the base iamge 
      # https://discuss.circleci.com/t/how-does-the-node-browsers-image-work/17449
      - run: 
          name: update chrome
          command: |
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb; sudo apt-get -fy install
          
      - run: npm install
      - run: cd browser-tests && npm install

      - save_cache:
          paths:
            - node_modules
            - browser-tests/node_modules
          key: v1-dependencies-{{ checksum "package.json" }}{{ checksum "browser-tests/package.json" }}

      # run tests!
      - run: npm -s run ci
      - run: cd browser-tests && npm -s run test
